### ISSUE TITLE
Open or close roller shutters partially

### ISSUE THREAD

**Issue by Sunrise17** [ageorgios/homebridge-tasmota-mqtt-motor#1]
Dear @ageorgios ,

As you may know well that with using Backlog and Delay commands, for example, if you shutter is closed and total opening time is 40 seconds, you should use 20 seconds ON time to open it 50%, setting delay to 200(0.1 second increment), so you can send:

Backlog Power2 ON; Delay 200; Power2 OFF

Is it possible to open or close shutters partially with your "homebridge-tasmota-mqtt-motor" plugin?

Thanks..

**Comment by ageorgios** [comment]
yes it works that way

**Comment by Sunrise17** [comment]
Dear @ageorgios ,

Thanks for your response, i want to let you know about one issue after my several tests. For ex, i am opening the window to 50% from homekit app, it opens successfully. After i have adjusted it to 20%, it closes completely to 0%. It can be some issue to calculate the correct remaining pulsetime. Tasmota ver [5.13.0](https://github.com/arendst/Sonoff-Tasmota/releases) is published and "Add display of remaining pulse time to command PulseTime (#2085)" property is added to new version. May be issue can be solved with that.

**Comment by ageorgios** [comment]
how many seconds is your duration for opening?
is your motor steady velocity or is it accelerating? steady velocity is assumed.
In my case of window, the commands you do 50%->20% work as expected.

**Comment by Sunrise17** [comment]
My shutters has steady velocity type. I still have not connected the switch to Motor yet, i am testing the switch on Home app right now.  When i reduce from 50% to 20%, home app shows, it closed completely. After movement, I am getting the current position = 0, in Homebridge log.

**Comment by Sunrise17** [comment]
close and opening duration, i have arranged 14 secs.

**Comment by Sunrise17** [comment]
Dear @ageorgios , as you have seen in the screenshot of my homebridge log that when window was fully opened, then i had adjusted it 55% , currenttargetposition arrived 55 but then it happened 42 automatically and then fully closed. I could not understand why it happened?? I will be glad if you can guide me about the issue. I think problem is caused by dragging the slider of Window in Home app. For ex, while dragging to 55%, it additionally sends the value of 65%, so multiple values allow switch to be closed completely. 

![screenshot ](https://user-images.githubusercontent.com/26038249/39835008-71856ff2-53d7-11e8-912a-b86f0f99c41a.JPG)

**Comment by Sunrise17** [comment]
Dear @ageorgios , second issue is about fully opening and closing of window. Regarding to screenshot below, when windows was fully opened, and i clicked "Power2 on" (for opening again), i am getting following debug which is correct,
`lastPosition = 100 PositionState = 1 currentTargetPosition = 100`
But then, when i clicked "Power1 on" (for closing), i am getting following status below,
`lastPosition = 100 PositionState = 0 currentTargetPosition = 100`

Normally, currentTargetPosition should be 0. I will be glad if you can solve the issue.

![ekran resmi 2018-05-09 23 39 39](https://user-images.githubusercontent.com/26038249/39838555-5f99d6ba-53e2-11e8-9727-8983a7fd3459.png)

**Comment by Sunrise17** [comment]
Dear @ageorgios , if your plugin memorized to which position shutter (or window) was last moved, and after next request (data) received, it can subtract and then decide "turn on time" only from the difference of both results (saved position - next request = turn on time). Otherwise, it confuses, slider in home app not commands correctly. I will be glad if you let me know about your solution. Thanks...

**Comment by ageorgios** [comment]
This is how it works:

Take a look:
https://github.com/ageorgios/homebridge-tasmota-mqtt-motor/blob/74398b83c2960687ce1a6558936e0b178d9ce2b0/index.js#L205-L214

Cannot understand why it does not work in your situation

**Comment by Sunrise17** [comment]
Dear @ageorgios , thanks for your quick response, while i started home bridge, i am receiving following warning ("WARNING":"Enable weblog 2 if response expected"), device weblog is also equals 2, is this normal?

![ekran resmi 2018-05-11 20 48 50](https://user-images.githubusercontent.com/26038249/39938824-e2b2921e-555c-11e8-8359-400e16746da4.png)
